version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/micro #where to store the artifacts
hooks:
  ApplicationStart:
    - location: scripts/start.sh #start script for the website
      timeout: 300
      runas: ec2-user
